In [10]:
import pandas as pd
import numpy as np

In [4]:
matches = pd.read_csv("dataset/all_matches.csv")

In [31]:
filter_1 = matches.loc[matches['venue'] == "MA Chidambaram Stadium"]
filter_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2130 entries, 150460 to 178319
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                2130 non-null   int64
 1   season                  2130 non-null   object
 2   start_date              2130 non-null   object
 3   venue                   2130 non-null   object
 4   innings                 2130 non-null   int64
 5   ball                    2130 non-null   float64
 6   batting_team            2130 non-null   object
 7   bowling_team            2130 non-null   object
 8   striker                 2130 non-null   object
 9   non_striker             2130 non-null   object
 10  bowler                  2130 non-null   object
 11  runs_off_bat            2130 non-null   int64
 12  extras                  2130 non-null   int64
 13  wides                   50 non-null     float64
 14  noballs                 14 non-null     float64
 15  byes                    2 non-null      float64
 16  legbyes                 20 non-null     float64
 17  penalty                 0 non-null      float64
 18  wicket_type             100 non-null    object
 19  player_dismissed        100 non-null    object
 20  other_wicket_type       0 non-null      float64
 21  other_player_dismissed  0 non-null      float64
dtypes: float64(8), int64(4), object(10)
memory usage: 382.7+ KB

In [32]:
filter_2 = filter_1.loc[filter_1['batting_team'] == "Mumbai Indians"]
filter_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 175171 to 178319
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                236 non-null    int64
 1   season                  236 non-null    object
 2   start_date              236 non-null    object
 3   venue                   236 non-null    object
 4   innings                 236 non-null    int64
 5   ball                    236 non-null    float64
 6   batting_team            236 non-null    object
 7   bowling_team            236 non-null    object
 8   striker                 236 non-null    object
 9   non_striker             236 non-null    object
 10  bowler                  236 non-null    object
 11  runs_off_bat            236 non-null    int64
 12  extras                  236 non-null    int64
 13  wides                   5 non-null      float64
 14  noballs                 0 non-null      float64
 15  byes                    0 non-null      float64
 16  legbyes                 2 non-null      float64
 17  penalty                 0 non-null      float64
 18  wicket_type             8 non-null      object
 19  player_dismissed        8 non-null      object
 20  other_wicket_type       0 non-null      float64
 21  other_player_dismissed  0 non-null      float64
dtypes: float64(8), int64(4), object(10)
memory usage: 42.4+ KB

In [33]:
filter_3 = filter_2.loc[filter_2['ball'] < 6]
filter_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74 entries, 175171 to 178243
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                74 non-null     int64
 1   season                  74 non-null     object
 2   start_date              74 non-null     object
 3   venue                   74 non-null     object
 4   innings                 74 non-null     int64
 5   ball                    74 non-null     float64
 6   batting_team            74 non-null     object
 7   bowling_team            74 non-null     object
 8   striker                 74 non-null     object
 9   non_striker             74 non-null     object
 10  bowler                  74 non-null     object
 11  runs_off_bat            74 non-null     int64
 12  extras                  74 non-null     int64
 13  wides                   2 non-null      float64
 14  noballs                 0 non-null      float64
 15  byes                    0 non-null      float64
 16  legbyes                 0 non-null      float64
 17  penalty                 0 non-null      float64
 18  wicket_type             3 non-null      object
 19  player_dismissed        3 non-null      object
 20  other_wicket_type       0 non-null      float64
 21  other_player_dismissed  0 non-null      float64
dtypes: float64(8), int64(4), object(10)
memory usage: 13.3+ KB

In [34]:
filter_3

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
175171,1178419,2019,2019-04-26,MA Chidambaram Stadium,1,0.1,Mumbai Indians,Chennai Super Kings,RG Sharma,Q de Kock,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175172,1178419,2019,2019-04-26,MA Chidambaram Stadium,1,0.2,Mumbai Indians,Chennai Super Kings,RG Sharma,Q de Kock,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175173,1178419,2019,2019-04-26,MA Chidambaram Stadium,1,0.3,Mumbai Indians,Chennai Super Kings,Q de Kock,RG Sharma,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175174,1178419,2019,2019-04-26,MA Chidambaram Stadium,1,0.4,Mumbai Indians,Chennai Super Kings,Q de Kock,RG Sharma,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175175,1178419,2019,2019-04-26,MA Chidambaram Stadium,1,0.5,Mumbai Indians,Chennai Super Kings,RG Sharma,Q de Kock,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178239,1181764,2019,2019-05-07,MA Chidambaram Stadium,2,5.2,Mumbai Indians,Chennai Super Kings,SA Yadav,Ishan Kishan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178240,1181764,2019,2019-05-07,MA Chidambaram Stadium,2,5.3,Mumbai Indians,Chennai Super Kings,Ishan Kishan,SA Yadav,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178241,1181764,2019,2019-05-07,MA Chidambaram Stadium,2,5.4,Mumbai Indians,Chennai Super Kings,Ishan Kishan,SA Yadav,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178242,1181764,2019,2019-05-07,MA Chidambaram Stadium,2,5.5,Mumbai Indians,Chennai Super Kings,Ishan Kishan,SA Yadav,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178243,1181764,2019,2019-05-07,MA Chidambaram Stadium,2,5.6,Mumbai Indians,Chennai Super Kings,Ishan Kishan,SA Yadav,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN